### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by seferov**
- base abstract request class
- type hinting
- CS fix

### CODE REVIEW

**Comment by lkraav** [comment]
Is `GuzzleHttp` somehow better than WP core's recently integrated `Requests` library?

**Comment by seferov** [comment]
@lkraav I don't have much experience with WP but as far as I know, it is.

**Comment by lkraav** [comment]
> I don't have much experience with WP but as far as I know, it is.

OK. Would love to hear a few specifics, if anybody knows.

**Comment by seferov** [comment]
Any comments?

**Pull request closed without merging**
