### PR TITLE
Improved .gitignore / Added extraGuzzleRequestsOptions (optional)

### PR DESCRIPTION
**Pull request by lucianocn**
Reference: Issue #205

### CODE REVIEW

**Comment by Skaelv** [comment]
Sorry for taking so long to review this @lucianocn 
Nice work 👍  Would be great to have it tested in [IntercomClientTest](https://github.com/intercom/intercom-php/blob/master/test/IntercomClientTest.php). 
Let me know if you want to add it. If not I'll be happy to take a look whenever I have some time.

**Comment by choran** [comment]
Hi @lucianocn 
Just checking in to see if you got any chance to add a test for this?
We can try and add it also but just wanted to check with you in the meantime

**Comment by choran** [comment]
Hi @lucianocn 
Just closing this since added unit test for this in separate PR #232 and merged changes via that PR

**Comment by lucianocn** [comment]
@Skaelv @choran sorry for my delay! Nice job guys ;)

**Pull request closed without merging**
