### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by bobjflong**

### CODE REVIEW

**Comment by dannyfallon** [comment]
There are benefits to having a service-config oriented approach as in the current version, mostly around defining new endpoints with a minimum of code changes or fat modelling; it's how AWS define their own API clients - see https://github.com/aws/aws-sdk-php/tree/master/src/data

Was there any particular reason why we opted not to do that this time around?

**Comment by bobjflong** [comment]
@dannyfallon the reason is maintainability. Guzzle changed their interface and testing infra in one version and left us with a huge rewrite on our hands. I want to protect us against this in future. With this structure I am much more confident in our ability to deal with dependency changes, and API changes with minimum/no fuss.

Additionally this new structure is much simpler, and similar to how the other clients are put together (intercom-node is the closest analogue).

**Comment by dannyfallon** [comment]
Sorry I never came back to you on this one Bob.You're making a good argument here both in terms of maintainability and protecting ourselves from our dependencies, thanks for the response :+1:

**Comment by bobjflong** [comment]
Haven't had any bug reports so going to merge this!

**Pull request merged**
