### PR TITLE
prevent guzzle from catching 404 as Page Not Found

### PR DESCRIPTION
**Pull request by Skaelv**
https://github.com/intercom/intercom-php/issues/185

@bobjflong

### CODE REVIEW

**Comment by bobjflong** [comment]
Tbh I'm not sure I understand the motivation for this. In HTTP, if a resource is not found the correct thing to do is to return a 404 error. Guzzle then raises an exception which can be caught. This is similar to the Ruby gem which uses errors: https://github.com/intercom/intercom-ruby#errors.

In this change we basically require the developer to inspect the returned object to decide if it is valid or not. That seems less convenient to me than a noisy exception?

At the very least this would need to be a new major version, but I still don't really understand why we need this vs. exceptions. Perhaps I've misunderstood something.

**Comment by Skaelv** [comment]
You made a good point. I wasn't sure it was the right way to go and wanted your advise on this.

At least this provides a good example to @kahuwi of how to catch this exception properly if he wants to.

**Comment by bobjflong** [comment]
Perhaps the readme could use a dedicated section on how to handle errors in the SDK, using code like yours here.

**Comment by Skaelv** [comment]
I'm adding a PR this. Thks bob

**Comment by Skaelv** [comment]
https://github.com/intercom/intercom-php/pull/199

**Pull request closed without merging**
