### PR TITLE
Re-support for PHP 5.5

### PR DESCRIPTION
**Pull request by xewl**
Proposal for #146

### CODE REVIEW

**Comment by etelford** [comment]
I was about to fork my own version because we have this same need on my team. +1

**Comment by pitpit** [comment]
Hi @xewl,

I think **composer.json** should also be changed to downgrade requirement ` "php": ">= 5.6"`

**Comment by xewl** [comment]
According to #148 support for 5.4 is also true.
Changed composer.json & readme

**Comment by tiagovb** [comment]
+1 @intercom, would you please pay attention to the fact that many projects still remains on php 5.5, and having our integration to intercom delayed takes us a step back on buy your products.

**Comment by bobjflong** [comment]
Hi @thiagotalma 

We've decided to not support PHP 5.5 as it is no longer officially supported, and is no longer receiving security updates: http://php.net/supported-versions.php

There are some 3rd party packages that promise backwards compatibility, that you may want to evaluate: https://packagist.org/packages/gayanhewa/intercom-php

Bob

**Comment by thiagotalma** [comment]
thanks @bobjflong !

**Comment by etelford** [comment]
For those interested, I've created a 5.5 fork here: https://github.com/etelford/intercom-php55

**Comment by mmartinic** [comment]
Closing this as it won't be merged.

**Pull request closed without merging**
